// <auto-generated />
using AlunosAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlunosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240520132659_PopulaTabela")]
    partial class PopulaTabela
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlunosAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nerevarine@gmail.com",
                            Idade = 30,
                            Nome = "Nerevarine"
                        },
                        new
                        {
                            Id = 2,
                            Email = "miraak@gmail.com",
                            Idade = 45,
                            Nome = "Miraak"
                        },
                        new
                        {
                            Id = 3,
                            Email = "martin@gmail.com",
                            Idade = 32,
                            Nome = "Martin Septim"
                        },
                        new
                        {
                            Id = 4,
                            Email = "barenziah@gmail.com",
                            Idade = 50,
                            Nome = "Barenziah"
                        },
                        new
                        {
                            Id = 5,
                            Email = "divayth@gmail.com",
                            Idade = 4000,
                            Nome = "Divayth Fyr"
                        },
                        new
                        {
                            Id = 6,
                            Email = "jagar@gmail.com",
                            Idade = 60,
                            Nome = "Jagar Tharn"
                        },
                        new
                        {
                            Id = 7,
                            Email = "nocturnal@gmail.com",
                            Idade = 1000,
                            Nome = "Nocturnal"
                        },
                        new
                        {
                            Id = 8,
                            Email = "lucien@gmail.com",
                            Idade = 45,
                            Nome = "Lucien Lachance"
                        },
                        new
                        {
                            Id = 9,
                            Email = "sheogorath@gmail.com",
                            Idade = 1000,
                            Nome = "Sheogorath"
                        },
                        new
                        {
                            Id = 10,
                            Email = "almalexia@gmail.com",
                            Idade = 3000,
                            Nome = "Almalexia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
